### PR TITLE
Update ci, ruby, rails  and remove lockfiles

### LINKED ISSUE #21: Drop EOL Rails versions
4.0 and 4.1 have reached EOL, we can comfortably drop them.

### PR DESCRIPTION
**Pull request by stoivo**
fix #21 #22 #23 #24

### CODE REVIEW

**Comment by teoljungberg** [comment]
Hi @stoivo Can you split this up into multiple PRs? This PR feels as if it's doing too many things at once.

I'd ideally like 1 per issue.

**Comment by stoivo** [comment]
I splited it it up some more 
Some include more commits but I tried to separate
- removing gem lockfiles https://github.com/teoljungberg/fx/pull/29
- update ruby https://github.com/teoljungberg/fx/pull/30
- update rails https://github.com/teoljungberg/fx/pull/31

**Comment by stoivo** [comment]
Any chanse you will be able to take a look at this this week?

**Comment by teoljungberg** [comment]
@stoivo It's on my list to do on friday. Thanks for the nudge.

**Comment by stoivo** [comment]
Any Update?

**Comment by teoljungberg** [comment]
I'll merge the PRs individually, so I'll close this PR.

**Pull request closed without merging**
