### PR TITLE
Dump functions in the beginning of the schema.rb

### PR DESCRIPTION
**Pull request by sobrinho**
Otherwise, we can't use functions as default values for columns.

Note that this does not block functions to query against tables that
will be created later in the schema since functions validate in runtime
instead of creation.

Closes #42.

### CODE REVIEW

**Comment by sobrinho** [comment]
@teoljungberg ping

**Comment by teoljungberg** [comment]
As mentioned in a previous PR - I'd like this to be hidden behind a configuration flag as I don't see it necessary being the required behavior.

**Comment by sobrinho** [comment]
@teoljungberg is required, otherwise, we can't use custom functions as default values for tables.

This is to follow the principle of least surprise, I should not be required to set a configuration to make the gem work when I create a custom function and use it as a default value.

A beginner won't guess it is needed easily and we have no side effects by dumping functions firstly.

**Comment by teoljungberg** [comment]
It's not required if you want to use the library for functions + triggers, which is what the library was built for in the first place.

As someone who uses the library for that - I don't want to see functions and trigger show up first in the schema list then they are not as important.

**Comment by sobrinho** [comment]
I still gently disagree because:

1. I do not expect to have to configure the library for a general use case such as functions as default values
1. The library manages functions and triggers elegantly and I wouldn't expect the library to be used only for functions AND triggers
1. There is no other similar library just for functions (what would be the point if we have this one)
1. Functions being dumped in the beginning won't hurt at all
1. Triggers are still dumped at the end of the schema, only functions goes up

🙈

**Comment by teoljungberg** [comment]
I think a configuration option is the middle ground in this discussion and it lets us roll out this without it being a breaking or surprising change to anyone.

We'll see about making it the default in a major version bump.

**Comment by sobrinho** [comment]
Alright, let me add the config then 👍

**Comment by sobrinho** [comment]
@teoljungberg tell me what you think :heart:

**Comment by sobrinho** [comment]
@teoljungberg can you restart the build? It failed to try to pull the fx.

**Comment by teoljungberg** [comment]
Push and empty commit and it will rebuild itself

**Comment by sobrinho** [comment]
@teoljungberg done!

**Comment by teoljungberg** [comment]
Looks good, can you update the PR description with more details as well as updating the readme documenting this feature?

**Comment by jrochkind** [comment]
Oh, I see there's another PR too, this replaces #42?

I personally don't understand why anyone would want the prior behavior (functions dumped last), or why it would cause a problem to change it -- I agree that people would expect refering to functions as default values to just work. 

But I'll take it as a non-default configurable value, better than nothing! Can't use this gem at all without this. Very eager to see it merged and released, so I don't need to use a local fork or patch.

**Comment by jrochkind** [comment]
OK, tried this branch out -- it also works lovely for me, same as #42. 

The whitespace issue I noted on #42 applies here too, so I'll copy it over.  Please let me know if there's anything I can do to help, eager to see this in fx. 

Since the gem expected its create_function/create_trigger definitions to go at the end, it puts a newline above them, but not below. Which makes my schema.rb look like:

```ruby
  enable_extension "pgcrypto"
  enable_extension "plpgsql"


  create_function :some_function, sql_definition: <<-SQL
       CREATE OR REPLACE FUNCTION public.some_function ....
       ....
  SQL
  create_table "another_table" do |t|
```

Extra newline before the `create_function`, and then it could use a newline in between the SQL HEREDOC end, and the following `create_table`. 

It *works* fine, this doesn't effect functioning properly, just looks a little bit messy if looking at it.

**Comment by jrochkind** [comment]
PS: 

> We'll see about making it the default in a major version bump.

This is currently 0.5.0, so under semver has no expectation of pre-1.0 backwards compat anyway... but I would strongly support a 1.0 release, it's been around for a while now and is mature, would be nice to count on semver 1.0. 

(I still can't think of anything it would break to simply change this, or any reason it would cause a problem for anyone, while the current behavior causes a problem for lots of people...)

**Comment by sobrinho** [comment]
Good catch about the spacing @jrochkind, I will fix it!

**Comment by sobrinho** [comment]
Done!

**Comment by jrochkind** [comment]
I am super interested in this, which was first reported as a problem in June 2019, and seems like a pretty popular use case. I would love to see it merged and included in a release, which would also increase confidence that this gem is maintained. 

For now, not willing to wait, and thinking it's better than forking the gem, I have found this simple "monkey patch" works to get functions included in schema.rb first, so am considering using this in my project. 

```ruby
require 'fx/schema_dumper/function'

module Fx
  module SchemaDumper
    module Function
      def tables(stream)
        functions(stream)
        super
      end
    end
  end
end
```

**Comment by teoljungberg** [comment]
I have a few things I'd like to get out of the way to release this gem to a 1.0 release, this is included in that list. But, life is hectic right now and I can't focus on doing open source outside of work right now.

I agree that the monkey patch above is a simple and easy solution to get unblocked. I hope that's ok for everyone right now.

**Comment by dzirtusss** [comment]
Had to do even more:
```
require "fx/schema_dumper/function"

module Fx
  module SchemaDumper
    module Function
      def tables(stream)
        dumpable_functions_in_database.each do |function|
          stream.puts(function.to_schema) if functions_going_before_tables.include?(function.name)
        end
        stream.puts

        super

        stream.puts
        dumpable_functions_in_database.each do |function|
          stream.puts(function.to_schema) if functions_going_before_tables.exclude?(function.name)
        end
      end

      def functions_going_before_tables
        @functions_going_before_tables ||= ActiveRecord::Base.connection.select_rows(<<~SQL.squish).flatten
          SELECT DISTINCT proname
          FROM pg_proc JOIN pg_depend ON pg_proc.oid = pg_depend.refobjid
          WHERE EXISTS (SELECT 1 FROM pg_class WHERE oid = objid)
             OR EXISTS (SELECT 1 FROM pg_attrdef WHERE oid = objid)
        SQL
      end
    end
  end
end
```

Because actually there are all 3 types of table/function relations:
1) tables & function don't have relation (most common)
2) tables depends on functions - e.g. defaults, indexes,- discussed in this thread
3) functions depends on tables - this is actually what was not discussed here at all. I have stumbled upon it with pg-function that have input variable defined as table row type. This is not very common, but sometimes useful, e.g.:
```
CREATE TABLE some_table ....
CREATE FUNCTION (st some_table) .....
```
and which is raising `PG::UndefinedObject: ERROR:  type "some_table" does not exist` if table was not created before function.

So here:
- `(SELECT 1 FROM pg_class WHERE oid = objid)` checks for all "relation" types - tables, indexes, views, etc
- `(SELECT 1 FROM pg_attrdef WHERE oid = objid)` checks specially for defaults

Maybe it needs more checks ^^^, but I dunno where functions can be a dependency except those. As well this is easy extendable if needed, plus works fine for me atm, putting only necessary functions on top of tables and rest below.

Sure, if even more cross-dependent it may be more complex and topological analyses may be needed (but this is another huge story), not this time.

P.S. As well there is totally another story with functions dependent on each other, which is not solved in `fx` as well atm. Doing smth like this ^^^ may help also.

**Comment by teoljungberg** [comment]
I'm willing to go with this approach if this solves the use cases for all of you that have expressed the need for this feature.

Rather than reviewing the work and making small comments around styling, I'm going to revamp this work locally and commit it with @sobrinho as the co-committer.

@dzirtusss - you get a gold star for a very detailed write up. If you want to work with adding support for your described use-case, I'd entertain that in a separate PR.

**Comment by teoljungberg** [comment]
Merged as f1411fb

**Comment by jrochkind** [comment]
Just noticed this is merged, and looks like it's released as of 0.6.0. Hooray, thank you!

**Pull request closed without merging**
